apiVersion: v1
data:
  APP_DEBUG: dHJ1ZQ==
  APP_ENV: bG9jYWw=
  APP_KEY: YmFzZTY0Omw5NHdqaThqZ3lUeTdSckxIeUJuNGtPc0lhODRtWHRLNzBMOG5za1lsaG89
  APP_PATH_PREFIX_IS_DYNAMIC: dHJ1ZQ==
kind: Secret
metadata:
  name: nginx-secret-env
