apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lb-nginx
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageValue: 200Mi
        type: AverageValue
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lb-nginx
status:
  currentMetrics: null
  desiredReplicas: 0
