apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_KEY: base64:l94wji8jgyTy7RrLHyBn4kOsIa84mXtK70L8nskYlho=
  APP_PATH_PREFIX_IS_DYNAMIC: "true"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
