apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-04-20T17:10:00Z"
  labels:
    kubernetes.io/metadata.name: duong-ns
  name: duong-ns
  uid: adf87167-52f8-4afc-b518-4b863e9d73c0
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
